# Generated by Django 2.0.6 on 2018-07-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publised_date',
            new_name='published_date',
        ),
    ]
